=== Deptfortransport/TDP/TDPortal/Codebase/TransportDirect/Web/Web2/PageTransferDetails.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="PageTransferDetails" type="complexType2">
    </xs:element>
    <xs:complexType name="complexType1">
        <xs:sequence />
        <xs:attribute name="PageId" type="xs:string" use="required" />
        <xs:attribute name="PageURL" type="xs:string" use="required" />
        <xs:attribute name="BookmarkRedirect" type="xs:string" use="required" />
        <xs:attribute name="SpecificStateClass" type="xs:boolean" use="required" />
        <xs:attribute name="BookmarkValidJourneyRedirect" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:complexType name="complexType2">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="page" type="complexType1">
            </xs:element>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== Deptfortransport/TDP/TDPortal/Codebase/TransportDirect/Web/Web2/PageTransferDetails.xml
<?xml version="1.0" encoding="utf-8"?>
<PageTransferDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PageTransferDetails.xsd">
  <page PageId="InitialPage" PageURL="Home.aspx" BookmarkRedirect="InitialPage" SpecificStateClass="false" />
  <page PageId="JourneyPlannerInput" PageURL="JourneyPlanning/JourneyPlannerInput.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="false" />
  <page PageId="JourneyPlannerAmbiguity" PageURL="JourneyPlanning/JourneyPlannerAmbiguity.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="true" />
  <page PageId="WaitPage" PageURL="JourneyPlanning/WaitPage.aspx" BookmarkRedirect="WaitPage" SpecificStateClass="true" />
  <page PageId="JourneyPlannerLocationMap" PageURL="Maps/JourneyPlannerLocationMap.aspx" BookmarkRedirect="JourneyPlannerLocationMap" SpecificStateClass="true" />
  <page PageId="PrintableJourneyPlannerLocationMap" PageURL="JourneyPlanning/PrintableJourneyMapInput.aspx" BookmarkRedirect="JourneyPlannerLocationMap" SpecificStateClass="true" />
  <page PageId="JourneySummary" PageURL="JourneyPlanning/JourneySummary.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="true" BookmarkValidJourneyRedirect="JourneySummary" />
  <page PageId="JourneyDetails" PageURL="JourneyPlanning/JourneyDetails.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="true" BookmarkValidJourneyRedirect="JourneyDetails" />
  <page PageId="JourneyMap" PageURL="JourneyPlanning/JourneyMap.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="true" BookmarkValidJourneyRedirect="JourneyMap" />
  <page PageId="JourneyFares" PageURL="JourneyPlanning/JourneyFares.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="false" BookmarkValidJourneyRedirect="JourneyFares" />
  <page PageId="JourneyAdjust" PageURL="JourneyPlanning/JourneyAdjust.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="false" BookmarkValidJourneyRedirect="JourneyAdjust" />
  <page PageId="CompareAdjustedJourney" PageURL="JourneyPlanning/CompareAdjustedJourney.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="false" BookmarkValidJourneyRedirect="CompareAdjustedJourney" />
  <page PageId="DetailedLegMap" PageURL="JourneyPlanning/DetailedLegMap.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="false" BookmarkValidJourneyRedirect="DetailedLegMap" />
  <page PageId="PrintableJourneySummary" PageURL="JourneyPlanning/PrintableJourneySummary.aspx" BookmarkRedirect="PrintableJourneySummary" SpecificStateClass="false" BookmarkValidJourneyRedirect="PrintableJourneySummary" />
  <page PageId="PrintableJourneyDetails" PageURL="JourneyPlanning/PrintableJourneyDetails.aspx" BookmarkRedirect="PrintableJourneyDetails" SpecificStateClass="false" BookmarkValidJourneyRedirect="PrintableJourneyDetails" />
  <page PageId="PrintableJourneyMap" PageURL="JourneyPlanning/PrintableJourneyMap.aspx" BookmarkRedirect="PrintableJourneyMap" SpecificStateClass="false" BookmarkValidJourneyRedirect="PrintableJourneyMap" />
  <page PageId="PrintableJourneyMapInput" PageURL="JourneyPlanning/PrintableJourneyMapInput.aspx" BookmarkRedirect="PrintableJourneyMapInput" SpecificStateClass="false" />
  <page PageId="PrintableJourneyMapTile" PageURL="JourneyPlanning/PrintableJourneyMapTile.aspx" BookmarkRedirect="PrintableJourneyMapTile" SpecificStateClass="false" BookmarkValidJourneyRedirect="PrintableJourneyMapTile" />
  <page PageId="PrintableCompareAdjustedJourney" PageURL="JourneyPlanning/PrintableCompareAdjustedJourney.aspx" BookmarkRedirect="PrintableCompareAdjustedJourney" SpecificStateClass="false" BookmarkValidJourneyRedirect="PrintableCompareAdjustedJourney" />
  <page PageId="PrintableTicketRetailers" PageURL="JourneyPlanning/PrintableTicketRetailers.aspx" BookmarkRedirect="PrintableTicketRetailers" SpecificStateClass="false" BookmarkValidJourneyRedirect="PrintableTicketRetailers" />
  <page PageId="PrintableJourneyFares" PageURL="JourneyPlanning/PrintableJourneyFares.aspx" BookmarkRedirect="PrintableJourneyFares" SpecificStateClass="false" BookmarkValidJourneyRedirect="PrintableJourneyFares" />
  <page PageId="Feedback" PageURL="Feedback.aspx" BookmarkRedirect="Feedback" SpecificStateClass="false" />
  <page PageId="FeedbackInitialPage" PageURL="ContactUs/FeedbackInitialPage.aspx" BookmarkRedirect="FeedbackInitialPage" SpecificStateClass="false" />
  <page PageId="FeedbackPage" PageURL="ContactUs/FeedbackPage.aspx" BookmarkRedirect="FeedbackPage" SpecificStateClass="false" />
  <page PageId="ClaimsInputPage" PageURL="ContactUs/ClaimsInputPage.aspx" BookmarkRedirect="ClaimsInputPage" SpecificStateClass="false" />
  <page PageId="ClaimsErrorsPage" PageURL="ClaimsErrorsPage.aspx" BookmarkRedirect="ClaimsErrorsPage" SpecificStateClass="false" />
  <page PageId="ClaimPrintPage" PageURL="ContactUs/ClaimPrintPage.aspx" BookmarkRedirect="ClaimPrintPage" SpecificStateClass="false" />
  <page PageId="ContactUsPage" PageURL="ContactUs/ContactDetails.aspx" BookmarkRedirect="ContactUsPage" SpecificStateClass="false" />
  <page PageId="Help" PageURL="StaticNoPrint.aspx" BookmarkRedirect="Help" SpecificStateClass="false" />
  <page PageId="GeneralMaps" PageURL="GeneralMaps.aspx" BookmarkRedirect="GeneralMaps" SpecificStateClass="false" />
  <page PageId="SiteMap" PageURL="SiteMap.aspx" BookmarkRedirect="SiteMap" SpecificStateClass="false" />
  <page PageId="SiteMapDefault" PageURL="SiteMapDefault.aspx" BookmarkRedirect="SiteMap" SpecificStateClass="false" />
  <page PageId="NetworkMaps" PageURL="Maps/NetworkMaps.aspx" BookmarkRedirect="NetworkMaps" SpecificStateClass="false" />
  <page PageId="Links" PageURL="StaticNoPrint.aspx" BookmarkRedirect="Links" SpecificStateClass="false" />
  <page PageId="PrintableLinks" PageURL="StaticNoPrint.aspx" BookmarkRedirect="Links" SpecificStateClass="false" />
  <page PageId="LocationInformation" PageURL="JourneyPlanning/LocationInformation.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="true" BookmarkValidJourneyRedirect="LocationInformation" />
  <page PageId="Map" PageURL="MapsDefault.aspx" BookmarkRedirect="Map" SpecificStateClass="false" />
  <page PageId="Home" PageURL="Home.aspx" BookmarkRedirect="Home" SpecificStateClass="false" />
  <page PageId="BatchJourneyPlanner" PageURL="BatchJourneyPlanner/BatchJourneyPlanner.aspx" BookmarkRedirect="BatchJourneyPlanner" SpecificStateClass="false" />
  <page PageId="Admin" PageURL="BatchJourneyPlanner/Admin/Admin.aspx" BookmarkRedirect="Admin" SpecificStateClass="false" />
  <page PageId="TravelNews" PageURL="LiveTravel/TravelNews.aspx" BookmarkRedirect="TravelNews" SpecificStateClass="false" />
  <page PageId="PrintableTravelNews" PageURL="LiveTravel/PrintableTravelNews.aspx" BookmarkRedirect="PrintableTravelNews" SpecificStateClass="false" />
  <page PageId="DepartureBoards" PageURL="LiveTravel/DepartureBoards.aspx" BookmarkRedirect="DepartureBoards" SpecificStateClass="false" />
  <page PageId="HelpFullJP" PageURL="Help/HelpJourneyPlannerInput" BookmarkRedirect="HelpFullJP" SpecificStateClass="true" />
  <page PageId="PrintableHelpFullJP" PageURL="HelpFullJPrinter.aspx" BookmarkRedirect="PrintableHelpFullJP" SpecificStateClass="false" />
  <page PageId="TrafficMap" PageURL="Maps/TrafficMaps.aspx" BookmarkRedirect="TrafficMap" SpecificStateClass="false" />
  <page PageId="TicketRetailers" PageURL="JourneyPlanning/TicketRetailers.aspx" BookmarkRedirect="JourneyPlannerInput" SpecificStateClass="false" BookmarkValidJourneyRedirect="TicketRetailers" />
  <page PageId="PrintableTrafficMap" PageURL="Maps/PrintableTrafficMaps.aspx" BookmarkRedirect="TrafficMap" SpecificStateClass="false" />
  <page PageId="TicketRetailersHandOff" PageURL="JourneyPlanning/TicketRetailersHandOff.aspx" BookmarkRedirect="TicketRetailersHandOff" SpecificStateClass="false" />
  <page PageId="Error" PageURL="ErrorPage.aspx?abandon=true" BookmarkRedirect="Error" SpecificStateClass="false" />
  <page PageId="ErrorPageCookies" PageURL="ErrorPageCookies.aspx?abandon=true" BookmarkRedirect="ErrorPageCookies" SpecificStateClass="false" />
  <page PageId="SorryPage" PageURL="SorryPage.aspx?abandon=true" BookmarkRedirect="SorryPage" SpecificStateClass="false" />
  <page PageId="ClaimsPolicy" PageURL="ClaimsPolicy.aspx" BookmarkRedirect="ClaimsPolicy" SpecificStateClass="false" />
  <page PageId="Maintenance" PageURL="Maintenance.aspx" BookmarkRedirect="Maintenance" SpecificStateClass="false" />
  <page PageId="PrintableSoftContent" PageURL="StaticPrinterFriendly.aspx" BookmarkRedirect="PrintableSoftContent" SpecificStateClass="false" />
  <page PageId="ClaimsPolicyPrinter" PageURL="ClaimsPolicyPrinter.aspx" BookmarkRedirect="ClaimsPolicyPrinter" SpecificStateClass="false" />
  <page PageId="FindStationInput" PageURL="JourneyPlanning/FindAStationInput.aspx" BookmarkRedirect="FindStationInput" SpecificStateClass="false" />
  <page PageId="FindStationResults" PageURL="JourneyPlanning/FindStationResults.aspx" BookmarkRedirect="FindStationResults" SpecificStateClass="false" />
  <page PageId="FindStationMap" PageURL="JourneyPlanning/FindStationMap.aspx" BookmarkRedirect="FindStationMap" SpecificStateClass="false" />
  <page PageId="PrintableFindStationResults" PageURL="JourneyPlanning/PrintableFindStationResults.aspx" BookmarkRedirect="PrintableFindStationResults" SpecificStateClass="false" />
  <page PageId="PrintableFindStationMap" PageURL="JourneyPlanning/PrintableFindStationMap.aspx" BookmarkRedirect="PrintableFindStationMap" SpecificStateClass="false" />
  <page PageId="FindFlightInput" PageURL="JourneyPlanning/FindFlightInput.aspx" BookmarkRedirect="FindFlightInput" SpecificStateClass="false" />
  <page PageId="VersionViewer" PageURL="Viewer/VersionViewer.aspx" BookmarkRedirect="Home" SpecificStateClass="false" />
  <page PageId="LogViewer" PageURL="Viewer/LogViewer.aspx" BookmarkRedirect="Home" SpecificStateClass="false" />
