=== Deptfortransport/TDP/TDPortal/Gateway/xml/TravelNews.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Joe Morrissey (Atos Origin) -->
<!--W3C Schema generated by XMLSPY v2004 rel. 2 U (http://www.xmlspy.com)-->
<!-- Updated to include 'Route disruption' value     for vantive 3383491 -->
<!-- Updated to include 'Sea Crossing' value         for vantive 3401467 -->
<!-- Capitalised 'Route Disruption' value            for vantive 3405206 -->
<!-- Updated for new Trafficlink fields              for CCN485a Hierarchy and Times of Roadworks -->
<!-- Updated for TOIDs Affected fields				 for CCN0582 Real Time Information in Car Prototype -->
<xs:schema targetNamespace="http://www.transportdirect.info/travelnews" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.transportdirect.info/travelnews" elementFormDefault="qualified">
	<xs:element name="Region">
		<xs:complexType>
			<xs:attribute name="uid" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="25" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="regionName" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="25" />
						<xs:enumeration value="East Anglia" />
						<xs:enumeration value="East Midlands" />
						<xs:enumeration value="London" />
						<xs:enumeration value="North East" />
						<xs:enumeration value="North West" />
						<xs:enumeration value="South East" />
						<xs:enumeration value="South West" />
						<xs:enumeration value="West Midlands" />
						<xs:enumeration value="Yorkshire and Humber" />
						<xs:enumeration value="Scotland" />
						<xs:enumeration value="Wales" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="LocationRef">
		<xs:annotation>
			<xs:documentation>Future Requirement</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="locationCodeReference" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="ScopeOfArea">
		<xs:annotation>
			<xs:documentation>Future Requirement</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="coordinates" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="IncidentDataSource">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="50" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
  <xs:element name="stationsImpacted">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="station" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tocsImpacted">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="toc" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
	<xs:element name="TOIDAffected">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="50" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TOIDsAffected">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TOIDAffected" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Incident">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="stationsImpacted" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="tocsImpacted" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="Region" maxOccurs="unbounded" />
				<xs:element ref="LocationRef" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="ScopeOfArea" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="IncidentDataSource" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="TOIDsAffected" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="uid" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="25" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="parent_uid" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="25" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="incident_change_status" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="12" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="severity" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15" />
						<xs:enumeration value="Critical" />
						<xs:enumeration value="Serious" />
						<xs:enumeration value="Very Severe" />
						<xs:enumeration value="Severe" />
						<xs:enumeration value="Medium" />
						<xs:enumeration value="Slight" />
						<xs:enumeration value="Very Slight" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="carriageway_direction" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15" />
						<xs:enumeration value="both ways" />
						<xs:enumeration value="None" />
						<xs:enumeration value="Northbound" />
						<xs:enumeration value="Southbound" />
						<xs:enumeration value="Eastbound" />
						<xs:enumeration value="Westbound" />
						<xs:enumeration value="clockwise" />
						<xs:enumeration value="anticlockwise" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="road_number" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="publicTransportOperator" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="modeOfTransport" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="location" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="incidentType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="60" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="roadType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="headlineText" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="200" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="detailText" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="350" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="incidentStatus" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="1" />
						<xs:enumeration value="O" />
						<xs:enumeration value="P" />
						<xs:enumeration value="C" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="easting" type="xs:double" use="required" />
			<xs:attribute name="northing" type="xs:double" use="required" />
			<xs:attribute name="reportedDatetime" type="xs:dateTime" use="required" />
			<xs:attribute name="startDatetime" type="xs:dateTime" use="required" />
			<xs:attribute name="lastModifiedDatetime" type="xs:dateTime" use="required" />
			<xs:attribute name="clearedDatetime" type="xs:dateTime" use="optional" />
			<xs:attribute name="expiryDatetime" type="xs:dateTime" use="optional" />
			<xs:attribute name="daily_startDatetime" type="xs:time" use="optional" />
			<xs:attribute name="daily_endDatetime" type="xs:time" use="optional" />
			<xs:attribute name="daymask" type="xs:string" use="optional" />
			<xs:attribute name="locationCodeReference" type="xs:string" use="optional" />
			<xs:attribute name="sourceOfLocationData" type="xs:string" use="optional" />
			<xs:attribute name="areaScopeCoordinates" type="xs:string" use="optional" />
			<xs:attribute name="plannedIncident" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="TrafficAndTravelNewsData">
		<xs:annotation>
			<xs:documentation>TransportDirect IF00908 TravelNews Copyright Atos Origin 2011</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Incident" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="version" use="required" fixed="IF00908">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Deptfortransport/TDP/TDPortal/Codebase/TransportDirect/TravelNews/bin/Debug/TravelNews/ValidTravelNews.xml
<?xml version="1.0" encoding="UTF-8"?>
<TrafficAndTravelNewsData xmlns="http://www.transportdirect.info/travelnews" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.transportdirect.info/travelnews TravelNews.xsd" version="IF00908">
  <Incident uid="RTM3715583" parent_uid="0" incident_change_status="Unchanged" severity="Severe" carriageway_direction="Southbound" road_number="M6" incidentType="Closures and Lane Restrictions" modeOfTransport="Road" location="M6 Lancashire" incidentStatus="O" roadType="M" headlineText="M6 : Restriction Southbound at J27" detailText="Lane closed southbound between J27, Standish and J26, Orrell Interchange, slow traffic." reportedDatetime="2010-05-27T15:29:48" lastModifiedDatetime="2010-05-27T16:07:29" startDatetime="2010-05-27T15:29:48" expiryDatetime="2010-05-27T16:47:05" daily_startDatetime="00:00:00" daily_endDatetime="23:59:59" daymask="SuMoTuWeThFrSa" plannedIncident="false" easting="354138" northing="410580">
    <Region uid="RTM3715583" regionName="North West"/>
    <IncidentDataSource>Government Agency (86)</IncidentDataSource>
    <TOIDsAffected>
      <TOIDAffected>4000000009205515</TOIDAffected>
      <TOIDAffected>4000000009205517</TOIDAffected>
      <TOIDAffected>4000000009212484</TOIDAffected>
      <TOIDAffected>4000000009212496</TOIDAffected>
      <TOIDAffected>4000000009212511</TOIDAffected>
      <TOIDAffected>4000000009212512</TOIDAffected>
      <TOIDAffected>4000000009212519</TOIDAffected>
      <TOIDAffected>4000000009289717</TOIDAffected>
      <TOIDAffected>4000000009289718</TOIDAffected>
      <TOIDAffected>4000000009289724</TOIDAffected>
    </TOIDsAffected>
  </Incident>
  <Incident uid="RTM3695954" parent_uid="0" incident_change_status="Amended" severity="Slight" carriageway_direction="both ways" road_number="" incidentType="Cleared" modeOfTransport="Road" location="Mitford Street Filey, North Yorkshire" incidentStatus="C" roadType="U" headlineText="Filey: Road re-opened at Mitford Street" detailText="Road re-opened on Mitford Street both ways at the Chapel Street junction in Filey.. Until 1st June" reportedDatetime="2010-05-17T10:54:31" lastModifiedDatetime="2010-05-27T16:09:31" startDatetime="2010-05-24T00:00:00" expiryDatetime="2010-05-27T23:59:00" daily_startDatetime="00:00:00" daily_endDatetime="23:59:59" daymask="SuMoTuWeThFrSa" plannedIncident="false" easting="511697" northing="480818">
    <Region uid="RTM3695954" regionName="Yorkshire and Humber"/>
    <IncidentDataSource>Local Authority (19)</IncidentDataSource>
    <TOIDsAffected>
      <TOIDAffected>4000000026503226</TOIDAffected>
      <TOIDAffected>4000000026579089</TOIDAffected>
    </TOIDsAffected>
  </Incident>
  <Incident uid="RTM3709737" parent_uid="0" incident_change_status="Unchanged" severity="Medium" carriageway_direction="both ways" road_number="A3212" incidentType="Closures/ blockages" modeOfTransport="Road" location="A3212 Westminster, London" incidentStatus="O" roadType="A" headlineText="A3212 : Road closed at Westminster" detailText="Millbank closed both ways between the A3203 junction and the A302 junction in Westminster, following Tuesdays State Opening of Parliament. Until 6:00 on 28th May" reportedDatetime="2010-05-25T05:27:58" lastModifiedDatetime="2010-05-27T13:59:35" startDatetime="2010-05-25T00:00:00" expiryDatetime="2010-05-28T07:30:00" daily_startDatetime="00:00:00" daily_endDatetime="23:59:59" daymask="SuMoTuWeThFrSa" plannedIncident="false" easting="530245" northing="178973">
    <Region uid="RTM3709737" regionName="London"/>
    <IncidentDataSource>Camera (16)</IncidentDataSource>
    <TOIDsAffected>
      <TOIDAffected>4000000030099833</TOIDAffected>
      <TOIDAffected>4000000030237969</TOIDAffected>
      <TOIDAffected>4000000030237970</TOIDAffected>
      <TOIDAffected>4000000030237971</TOIDAffected>
      <TOIDAffected>4000000030237974</TOIDAffected>
      <TOIDAffected>4000000030417958</TOIDAffected>
      <TOIDAffected>4000000030418101</TOIDAffected>
      <TOIDAffected>4000000030418102</TOIDAffected>
      <TOIDAffected>4000000030418104</TOIDAffected>
      <TOIDAffected>4000000030458831</TOIDAffected>
      <TOIDAffected>4000000030458832</TOIDAffected>
    </TOIDsAffected>
  </Incident>
  <Incident uid="RTM3714052" parent_uid="0" incident_change_status="Unchanged" severity="Medium" carriageway_direction="None" road_number="A100" incidentType="Closures and Lane Restrictions" modeOfTransport="Road" location="A100 City Of London, London" incidentStatus="O" roadType="A" headlineText="A100 : Closure at City Of London" detailText="Bridge due to open at 16:45 and 18:00 on Tower Bridge Approach at the Tower Hill junction in City Of London, delays expected. Until 18:20 on 27th May" reportedDatetime="2010-05-27T05:47:28" lastModifiedDatetime="2010-05-27T16:08:57" startDatetime="2010-05-27T00:00:00" expiryDatetime="2010-05-27T16:50:00" daily_startDatetime="00:00:00" daily_endDatetime="23:59:59" daymask="SuMoTuWeThFrSa" plannedIncident="false" easting="533774" northing="180682">
    <Region uid="RTM3714052" regionName="London"/>
    <IncidentDataSource>Camera (16)</IncidentDataSource>
    <TOIDsAffected>
      <TOIDAffected>4000000030345773</TOIDAffected>
      <TOIDAffected>4000000030459778</TOIDAffected>
      <TOIDAffected>4000000030459779</TOIDAffected>
      <TOIDAffected>4000000031066867</TOIDAffected>
    </TOIDsAffected>
  </Incident>
  <Incident uid="RTM3714151" parent_uid="0" incident_change_status="Unchanged" severity="Medium" carriageway_direction="Westbound" road_number="A12" incidentType="Congestion" modeOfTransport="Road" location="A12 Ilford, Greater London" incidentStatus="O" roadType="A" headlineText="A12 : Congestion at Ilford" detailText="Queueing traffic on Eastern Avenue westbound at the Gants Hill Roundabout junction in Ilford." reportedDatetime="2010-05-27T06:08:09" lastModifiedDatetime="2010-05-27T15:46:25" startDatetime="2010-05-27T06:08:09" expiryDatetime="2010-05-27T16:26:25" daily_startDatetime="00:00:00" daily_endDatetime="23:59:59" daymask="SuMoTuWeThFrSa" plannedIncident="false" easting="543287" northing="188426">
    <Region uid="RTM3714151" regionName="London"/>
    <IncidentDataSource>Camera (16)</IncidentDataSource>
    <TOIDsAffected>
      <TOIDAffected>4000000030361667</TOIDAffected>
      <TOIDAffected>4000000031045989</TOIDAffected>
    </TOIDsAffected>
  </Incident>
  <Incident uid="RTM3714045" parent_uid="0" incident_change_status="Unchanged" severity="Medium" carriageway_direction="Westbound" road_number="A315" incidentType="Closures and Lane Restrictions" modeOfTransport="Road" location="A315 Knightsbridge, London" incidentStatus="O" roadType="A" headlineText="A315 : Restriction at Knightsbridge" detailText="One lane closed westbound at the Scotch Corner junction in Knightsbridge, slow traffic." reportedDatetime="2010-05-27T05:39:44" lastModifiedDatetime="2010-05-27T15:46:26" startDatetime="2010-05-27T05:39:44" expiryDatetime="2010-05-27T16:26:26" daily_startDatetime="00:00:00" daily_endDatetime="23:59:59" daymask="SuMoTuWeThFrSa" plannedIncident="false" easting="527778" northing="179695">
    <Region uid="RTM3714045" regionName="London"/>
    <IncidentDataSource>Government Agency (71)</IncidentDataSource>
    <TOIDsAffected>
      <TOIDAffected>4000000030960564</TOIDAffected>
      <TOIDAffected>4000000030960565</TOIDAffected>
    </TOIDsAffected>
  </Incident>
  <Incident uid="RTM3714041" parent_uid="0" incident_change_status="Unchanged" severity="Slight" carriageway_direction="both ways" road_number="" incidentType="Delays" modeOfTransport="Road" location="Torpoint Ferry Plymouth, Devon" incidentStatus="O" roadType="U" headlineText="Plymouth: Delays at Tamar Wharf" detailText="Waiting times of up to ten minutes on Tamar Wharf both ways between the A374 Pottery Road junction and the A374 junction in Plymouth, three ferries running." reportedDatetime="2010-05-27T05:32:25" lastModifiedDatetime="2010-05-27T15:56:39" startDatetime="2010-05-27T05:32:25" expiryDatetime="2010-05-27T16:36:39" daily_startDatetime="00:00:00" daily_endDatetime="23:59:59" daymask="SuMoTuWeThFrSa" plannedIncident="false" easting="244875" northing="55154">
    <Region uid="RTM3714041" regionName="South West"/>
    <IncidentDataSource>Operator (25)</IncidentDataSource>
    <TOIDsAffected></TOIDsAffected>
  </Incident>
  <Incident uid="RTM3710805" parent_uid="0" incident_change_status="Unchanged" severity="Medium" carriageway_direction="Westbound" road_number="A406" incidentType="Closures/ blockages" modeOfTransport="Road" location="A406 Brent Cross, Greater London" incidentStatus="O" roadType="A" headlineText="A406 : Slip road closed at Brent Cross" detailText="Exit slip road closed on North Circular Road westbound at the Brent Cross Flyover junction in Brent Cross, earlier building fire at a derelict property. Diversion in operation." reportedDatetime="2010-05-25T12:08:16" lastModifiedDatetime="2010-05-27T16:08:35" startDatetime="2010-05-25T12:08:16" expiryDatetime="2010-05-27T16:48:35" daily_startDatetime="00:00:00" daily_endDatetime="23:59:59" daymask="SuMoTuWeThFrSa" plannedIncident="false" easting="523556" northing="187934">
    <Region uid="RTM3710805" regionName="London"/>
    <IncidentDataSource>Camera (16)</IncidentDataSource>
    <TOIDsAffected>
      <TOIDAffected>4000000030225259</TOIDAffected>
    </TOIDsAffected>
  </Incident>
